//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGSA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.buy_Offer = new HashSet<buy_Offer>();
            this.sell_Offer = new HashSet<sell_Offer>();
        }
    
        public int ID { get; set; }
        public int product_owner { get; set; }
        public string Name { get; set; }
        public Nullable<double> rating { get; set; }
        public int stock { get; set; }
        public int sold_copies { get; set; }
        public Nullable<int> genre_id { get; set; }
        public Nullable<int> product_type_id { get; set; }
        public Nullable<int> condition_id { get; set; }
        public System.DateTime Update_Date { get; set; }
        public int Update_Who { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buy_Offer> buy_Offer { get; set; }
        public virtual dic_condition dic_condition { get; set; }
        public virtual dic_Genre dic_Genre { get; set; }
        public virtual dic_Product_type dic_Product_type { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sell_Offer> sell_Offer { get; set; }
    }
}
