//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGSA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sell_Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sell_Offer()
        {
            this.transactions = new HashSet<transactions>();
        }
    
        public int ID { get; set; }
        public int seller_id { get; set; }
        public Nullable<double> price { get; set; }
        public int amount { get; set; }
        public Nullable<System.DateTime> last_sell_date { get; set; }
        public string name { get; set; }
        public int buyed_copies { get; set; }
        public int product_id { get; set; }
        public int status_id { get; set; }
        public System.DateTime Update_Date { get; set; }
        public int Update_Who { get; set; }
    
        public virtual dic_Offer_status dic_Offer_status { get; set; }
        public virtual product product { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transactions> transactions { get; set; }
    }
}
