//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGSA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public int ID { get; set; }
        public int seller_id { get; set; }
        public int buyer_id { get; set; }
        public int buy_offer_id { get; set; }
        public int sell_offer_id { get; set; }
        public System.DateTime transaction_Date { get; set; }
        public int status_id { get; set; }
        public System.DateTime Update_Date { get; set; }
        public int Update_Who { get; set; }
    
        public virtual buy_Offer buy_Offer { get; set; }
        public virtual dic_Transaction_status dic_Transaction_status { get; set; }
        public virtual sell_Offer sell_Offer { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual users users2 { get; set; }
    }
}
