//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGSA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_Authetication
    {
        public int ID { get; set; }
        public int User_id { get; set; }
        public string password { get; set; }
        public System.DateTime Update_Date { get; set; }
        public int Update_Who { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
